# This is a basic workflow to help you get started with Actions

name: main
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: 
      - "*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: yarn install - frontend
        run: |
          cd frontend \
          yarn install
      
      - name: yarn install - backend
        run: |
          cd backend \
          yarn install

      # Runs a set of commands using the runners shell
      - name: build
        run: |
          cd frontend \
          yarn build \
          cd ../backend \
          yarn build
